# Generated by Django 5.2.6 on 2025-09-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_verified_student_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='code',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
