# Generated by Django 5.2.6 on 2025-09-24 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_invitation_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-created_at'], 'verbose_name': 'دعوة', 'verbose_name_plural': 'دعوات'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username'], 'verbose_name': 'ملف مستخدم', 'verbose_name_plural': 'ملفات المستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ['-updated_at'], 'verbose_name': 'إعداد الموقع', 'verbose_name_plural': 'إعدادات الموقع'},
        ),
    ]
