# Generated by Django 5.2.6 on 2025-09-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name'], 'verbose_name': 'مقرر', 'verbose_name_plural': 'مقررات'},
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم المقرر'),
        ),
    ]
