# Generated by Django 5.2.6 on 2025-09-23 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الواجب')),
                ('due_date', models.DateField(verbose_name='تاريخ التسليم')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'واجب',
                'verbose_name_plural': 'واجبات',
                'ordering': ['due_date'],
            },
        ),
    ]
