# Generated by Django 5.2.6 on 2025-09-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-due_date'], 'verbose_name': 'واجب', 'verbose_name_plural': 'واجبات'},
        ),
        migrations.AddField(
            model_name='assignment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الواجب'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(verbose_name='آخر موعد للتسليم'),
        ),
    ]
