# Generated by Django 5.2.6 on 2025-09-24 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_assignment_options_assignment_attachment_and_more'),
        ('courses', '0002_alter_course_options_alter_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course', verbose_name='المقرر'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(verbose_name='موعد التسليم'),
        ),
    ]
